default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: CAATO_dev

test:
  <<: *default
  database: CAATO_test

production:
  <<: *default
  database: CAATO_production
  username: CAATO
  password: <%= ENV["CAATO_DATABASE_PASSWORD"] %>
